# Generated by Django 5.2.8 on 2025-11-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('class_type', models.CharField(choices=[('yoga', 'Yoga'), ('pilates', 'Pilates'), ('spinning', 'Spinning'), ('hiit', 'HIIT'), ('strength', 'Strength Training'), ('cardio', 'Cardio'), ('crossfit', 'CrossFit'), ('dance', 'Dance')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('instructor', models.CharField(max_length=100)),
                ('schedule', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fitness Class',
                'verbose_name_plural': 'Fitness Classes',
                'ordering': ['schedule'],
            },
        ),
    ]
