# Generated by Django 4.2.27 on 2025-12-23 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_active_member',
        ),
        migrations.AddField(
            model_name='member',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Boy (cm)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kilo (kg)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('student', 'Student'), ('standard', 'Standard'), ('premium', 'Premium')], default='standard', help_text='Üyelik tipi fiyatlandırma motorunu etkiler.', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
